apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hpa
  name: php-apache
spec:
  selector:
    matchLabels:
      app: php-apache
  replicas: 3
  template:
    metadata:
      labels:
         app: php-apache
    spec:
      containers:
      - name: php-apache
        image: k8s.gcr.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m

apiVersion: v1
ki---nd: Service
metadata:
  namespace: hpa
  name: php-apache
  labels:
    app: php-apache
spec:
  ports:
  - port: 80
  selector:
    app: php-apache