apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sql-sa
  namespace: sql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-sql
  namespace: sql
spec:
  selector:
    matchLabels:
      app: demo-sql
  template:
    metadata:
      labels:
        app: demo-sql
    spec:
      serviceAccountName: demo-sql-sa
      containers:
      - name: demo-sql
        image: gcr.io/projectodemos/demo-sql:1.0.9
        env:
        - name: DB_HOST
          value: "10.3.0.6"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "academia" 
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "120m"
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        args:
        - "--private-ip"
        - "--structured-logs"
        - "--port=5432"
        - "projectodemos:us-central1:demo-privada"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu:    "1"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-sql
  namespace: sql
  labels:
    app: demo-sql
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: demo-sql
