---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
 name: aplicacion-a-cert
 namespace: aplicacion-a  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacion-a-deployment
  namespace: aplicacion-a
  labels:
    app: aplicacion-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplicacion-a
  template:
    metadata:
      labels:
        app: aplicacion-a
    spec:
      containers:
      - name: aplicacion-a
        image: us-central1-docker.pkg.dev/projectodemos/comunidad-gcp/aplicaciona:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: aplicacion-a-svc
  namespace: aplicacion-a
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: aplicacion-a 
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: aplicacion-a
---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: aplicacion-a-ingress
      namespace: aplicacion-a
      annotations:  
          networking.gke.io/managed-certificates: aplicacion-a-cert
          kubernetes.io/ingress.class: "gce"
    spec:
      defaultBackend:
        service:
          name: aplicacion-a-svc
          port:
            number: 80