---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
 name: aplicacion-b-cert
 namespace: aplicacion-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacion-b-deployment
  namespace: aplicacion-b
  labels:
    app: aplicacion-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplicacion-b
  template:
    metadata:
      labels:
        app: aplicacion-b
    spec:
      containers:
      - name: aplicacion-b
        image: us-central1-docker.pkg.dev/projectodemos/comunidad-gcp/aplicacionb:1.0.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: aplicacion-b-svc
  namespace: aplicacion-b
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: aplicacion-b 
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: aplicacion-b
---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: aplicacion-b-ingress
      annotations:  
          networking.gke.io/managed-certificates: aplicacion-b-cert
          kubernetes.io/ingress.class: "gce"
    spec:
      defaultBackend:
        service:
          name: aplicacion-b-svc
          port:
            number: 80